export const userData = [
    {
      name: 'Jan',
      "Active User": 4000,
    },
    {
        name: 'Feb',
        "Active User": 1000,
      },
      {
        name: 'Mar',
        "Active User": 5000,
      },
      {
        name: 'Apr',
        "Active User": 2000,
      },
      {
        name: 'May',
        "Active User": 1500,
      },
      {
        name: 'Jun',
        "Active User": 3000,
      },
      {
        name: 'Jul',
        "Active User": 4000,
      },
      {
        name: 'Aug',
        "Active User": 6000,
      },
      {
        name: 'Sep',
        "Active User": 2500,
      },
      {
        name: 'Oct',
        "Active User": 3000,
      },
      {
        name: 'Nov',
        "Active User": 2000,
      },
      {
        name: 'Dec',
        "Active User": 3500,
      },
  ];

export const userRows = [
    {
      id: 1,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 2,
      username: "John",
      avatar: "no-avatar.png",
      email: "john_wick@gmail.com",
      status: "active",
      transaction: "100.00€",
    },
    {
      id: 3,
      username: "Sammy",
      avatar: "female1.jpg",
      email: "icd_sammy@gmail.com",
      status: "active",
      transaction: "250.00€",
    },
    {
      id: 4,
      username: "Jessica",
      avatar: "female2.png",
      email: "hey_jessy@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 5,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 6,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 7,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 8,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 9,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 10,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 11,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 12,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 13,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 14,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 15,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
  ];

  export const productRows = [
    {
      id: 1,
      name: "Iphone 13 Pro",
      image: "iphone13pro.jpg",
      description: "L'iPhone 13 Pro d'Apple est un smartphone ultra haut de gamme doté d'un écran de 6,1 pouces. Doté de la technologie ProMotion, il dispose d'un taux de rafraîchissement adaptatif pouvant varier entre 10 et 120 Hz. Doté d'un triple module caméra ultra sophistiqué avec des équivalents 13 mm, 26 mm et 77 mm, ce smartphone utilise la puce A15 Bionic. Il existe en versions 128 Go, 256 Go, 512 Go ou 1 To de stockage.",
      stock: "200",
      price: "1 250.00€",
    },
    {
      id: 2,
      name: "Iphone 13",
      image: "iphone13.jpeg",
      description: "L'iPhone 13 est un smartphone haut de gamme signé Apple et compatible 5G. Décliné en cinq couleurs, il embarque le processeur A15 Bionic, 128 Go de stockage au minimum et un double module caméra avec grand-angle et ultra grand-angle. Son écran OLED mesure 6,1 pouces et est compatible HDR Dolby Vision. ",
      stock: "300",
      price: "850.00€",
    },
    {
      id: 3,
      name: "Samsung Galaxy Z Fold 3",
      image: "samsung-fold3.jpg",
      description: "Le Samsung Galaxy Z Fold 3 est une tablette capable de se transformer en un smartphone. Doté d'un grand écran pliant de 7,6 pouces, cet appareil peut devenir un mobile compact arborant une diagonale de 6,2 pouces une fois refermé, tel un livre. Très bien équipé (Snapdragon 888, 12 Go de RAM, 256 ou 512 Go de stockage), il est aussi le premier appareil Samsung avec une caméra frontale sous l'écran. Il supporte le stylet S-Pen. ",
      stock: "150",
      price: "1 299.00€",
    },
    {
      id: 4,
      name: "Samsung Galaxy Z Flip 3",
      image: "samsung-galaxy-flip3.jpg",
      description: "Le Samsung Galaxy Z Flip 3 est un smartphone pliant doté d'un écran de 6,7 pouces. Capable de se refermer comme un téléphone à clapet, ce mobile se destine à celles et ceux qui cherchent un appareil très facile à transporter. Il fonctionne sous  Android 11, embarque 8 Go de RAM et 128 Go ou 256 Go de stockage interne. Il intègre une batterie de 3300 mAh.",
      stock: "150",
      price: "799.00€",
    },
  ];