export const userData = [
    {
      name: 'Jan',
      "Active User": 4000,
    },
    {
        name: 'Feb',
        "Active User": 1000,
      },
      {
        name: 'Mar',
        "Active User": 5000,
      },
      {
        name: 'Apr',
        "Active User": 2000,
      },
      {
        name: 'May',
        "Active User": 1500,
      },
      {
        name: 'Jun',
        "Active User": 3000,
      },
      {
        name: 'Jul',
        "Active User": 4000,
      },
      {
        name: 'Aug',
        "Active User": 6000,
      },
      {
        name: 'Sep',
        "Active User": 2500,
      },
      {
        name: 'Oct',
        "Active User": 3000,
      },
      {
        name: 'Nov',
        "Active User": 2000,
      },
      {
        name: 'Dec',
        "Active User": 3500,
      },
  ];

export const userRows = [
    {
      id: 1,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 2,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 3,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 4,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 5,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 6,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 7,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 8,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 9,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 10,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 11,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 12,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 13,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 14,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
    {
      id: 15,
      username: "Jack",
      avatar: "male1.png",
      email: "jack@gmail.com",
      status: "active",
      transaction: "50.00€",
    },
  ];